import { describe, expect, it } from "vitest";
import {
  AUDIO_FRAME_HEADER_BYTES,
  controlMessage,
  decodeAudioFrame,
  encodeAudioFrame,
  errorMessage,
  MSG_HELLO,
  PROTOCOL_VERSION,
} from "@shared/protocol";

describe("audio frame encode/decode", () => {
  it("round-trips sequence, sample rate, and samples exactly", () => {
    const samples = new Float32Array([0, 0.5, -0.5, 1, -1, 0.25]);
    const encoded = encodeAudioFrame(42, 22050, samples);
    expect(encoded.byteLength).toBe(AUDIO_FRAME_HEADER_BYTES + samples.length * 4);

    const decoded = decodeAudioFrame(encoded);
    expect(decoded.sequence).toBe(42);
    expect(decoded.sampleRate).toBe(22050);
    expect(Array.from(decoded.samples)).toEqual(Array.from(samples));
  });

  it("matches the exact byte layout of ai-worker's struct.Struct('<II') header", () => {
    const encoded = encodeAudioFrame(1, 16000, new Float32Array([1]));
    const view = new DataView(encoded);
    expect(view.getUint32(0, true)).toBe(1); // sequence, LE
    expect(view.getUint32(4, true)).toBe(16000); // sample_rate, LE
    expect(view.getFloat32(8, true)).toBeCloseTo(1, 5); // PCM starts at byte 8
  });

  it("handles sequence 0 and empty sample arrays", () => {
    const encoded = encodeAudioFrame(0, 22050, new Float32Array([]));
    const decoded = decodeAudioFrame(encoded);
    expect(decoded.sequence).toBe(0);
    expect(decoded.samples.length).toBe(0);
  });

  it("rejects frames shorter than the 8-byte header", () => {
    expect(() => decodeAudioFrame(new ArrayBuffer(4))).toThrow(/too short/);
  });

  it("handles a large uint32 sequence without overflow", () => {
    const big = 0xfffffffe;
    const decoded = decodeAudioFrame(encodeAudioFrame(big, 22050, new Float32Array([0])));
    expect(decoded.sequence).toBe(big);
  });
});

describe("cross-language wire compatibility", () => {
  it("decodes bytes actually produced by ai-worker/app/server/protocol.py (golden fixture)", () => {
    // Generated by running, against the real Python module:
    //   protocol.encode_audio_frame(42, 22050, np.array([0, 0.5, -0.5, 1, -1, 0.25], dtype="float32"))
    // This is not a re-derivation of our own encoder — it is bytes from the
    // actual source-of-truth implementation, proving the TS decoder reads
    // exactly what ai-worker writes.
    const hex = "2a00000022560000000000000000003f000000bf0000803f000080bf0000803e";
    const bytes = new Uint8Array(hex.match(/../g)!.map((b) => parseInt(b, 16)));
    const decoded = decodeAudioFrame(bytes.buffer);
    expect(decoded.sequence).toBe(42);
    expect(decoded.sampleRate).toBe(22050);
    expect(Array.from(decoded.samples)).toEqual([0, 0.5, -0.5, 1, -1, 0.25]);
  });

  it("encodes bytes byte-for-byte identical to the real Python encoder's output", () => {
    const expectedHex = "2a00000022560000000000000000003f000000bf0000803f000080bf0000803e";
    const samples = new Float32Array([0, 0.5, -0.5, 1, -1, 0.25]);
    const encoded = encodeAudioFrame(42, 22050, samples);
    const actualHex = Array.from(new Uint8Array(encoded))
      .map((b) => b.toString(16).padStart(2, "0"))
      .join("");
    expect(actualHex).toBe(expectedHex);
  });
});

describe("errorMessage", () => {
  it("matches the real Python error_message() output shape exactly", () => {
    // Generated by: protocol.error_message("req-9", "BACKPRESSURE", "queue full")
    const expected = {
      version: 1,
      type: "engine.error",
      request_id: "req-9",
      code: "BACKPRESSURE",
      message: "queue full",
    };
    expect(errorMessage("req-9", "BACKPRESSURE", "queue full")).toEqual(expected);
  });

  it("omits request_id when null (spontaneous binary-frame errors)", () => {
    const msg = errorMessage(null, "NO_STREAM_OPEN", "Send stream.open before audio frames");
    expect("request_id" in msg).toBe(false);
  });
});

describe("controlMessage", () => {
  it("always includes version and type, omits request_id when not given", () => {
    const msg = controlMessage(MSG_HELLO, undefined);
    expect(msg).toEqual({ version: PROTOCOL_VERSION, type: MSG_HELLO });
    expect("request_id" in msg).toBe(false);
  });

  it("includes request_id and extra fields when given", () => {
    const msg = controlMessage("engine.load_voice", "req-1", {
      voice_profile_id: "abc",
      reference_paths: ["/tmp/a.wav"],
    });
    expect(msg).toEqual({
      version: PROTOCOL_VERSION,
      type: "engine.load_voice",
      request_id: "req-1",
      voice_profile_id: "abc",
      reference_paths: ["/tmp/a.wav"],
    });
  });
});
