"""create voice enrollment tables

Revision ID: b246d427fb06
Revises:
Create Date: 2026-08-25 00:08:19.050309

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b246d427fb06"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "voice_profiles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "RECORDING",
                "PROCESSING",
                "READY_FOR_AI_PROCESSING",
                "FAILED",
                "ARCHIVED",
                name="voice_profile_status",
            ),
            nullable=False,
        ),
        sa.Column("consent_confirmed", sa.Boolean(), nullable=False),
        sa.Column("consent_confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_voice_profiles_user_id"), "voice_profiles", ["user_id"], unique=False)
    op.create_table(
        "voice_samples",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("voice_profile_id", sa.UUID(), nullable=False),
        sa.Column("storage_key", sa.String(length=512), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("sample_rate", sa.Integer(), nullable=True),
        sa.Column("channels", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "UPLOADED", "VALIDATING", "VALID", "INVALID", "DELETED", name="voice_sample_status"
            ),
            nullable=False,
        ),
        sa.Column("validation_error", sa.String(length=1000), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["voice_profile_id"], ["voice_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_voice_samples_voice_profile_id"),
        "voice_samples",
        ["voice_profile_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_voice_samples_voice_profile_id"), table_name="voice_samples")
    op.drop_table("voice_samples")
    op.drop_index(op.f("ix_voice_profiles_user_id"), table_name="voice_profiles")
    op.drop_table("voice_profiles")
    op.drop_table("users")
    # ### end Alembic commands ###

    # Postgres ENUM types are not dropped automatically when the columns/tables
    # using them are dropped — clean them up explicitly so downgrade -> upgrade
    # round-trips cleanly.
    sa.Enum(name="voice_sample_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="voice_profile_status").drop(op.get_bind(), checkfirst=True)
